import os

ORDER_NUM = os.getenv('HUEMID_ORDER_NUM')
SECURITY_CODE = os.getenv('HUEMID_SECURITY_CODE')
TG_BOT_TOKEN = os.getenv('HUEMID_TG_BOT_TOKEN')
TG_CHAT_ID = os.getenv('HUEMID_TG_CHAT_ID')
ANTI_CAPTCHA_KEY = os.getenv('HUEMID_ANTI_CAPTCHA_KEY')
